### ISSUE TITLE
Fold/unfold also happens by right click

### ISSUE THREAD

**Issue by girgink** [martinRenou/jupyterlab-unfold#17]
Right click to a folder name displays the context menu as expected, but it also triggers fold/unfold. Can you please limit folding/unfolding to left click only?

**Comment by martinRenou** [comment]
We are making this an option and you should be able to change the settings of jupyterlab-unfold to get folding/unfolding for the left-click instead

**Comment by martinRenou** [comment]
`pip install 0.1.5`

![settings](https://user-images.githubusercontent.com/21197331/129545791-35416522-3b75-4501-9b6c-0a55c91eaad9.gif)

**Comment by girgink** [comment]
Hi @martinRenou Thanks for the setting. This solves the issue with the folders, but unfortunately breaks double-click to open for files. After I set `singleClickToUnfold: false`, double clicking files does nothing.

**Comment by martinRenou** [comment]
Thanks for your comment. Indeed, the latest release seems broken. I will push a fix ASAP.

**Comment by martinRenou** [comment]
Fixed in 0.1.6
